### ISSUE TITLE
NLU-NLG Project description

### ISSUE THREAD

**Issue by secretsauceai** [secretsauceai/secret_sauce_ai#12]
# Description

The NLU-NLG project requires a rough outline containing:

- more research into solutions
    - What? Scope?
- definition of deliverables
    - What tools, documentation, models, etc. are to be used and what is to be built?
- scope of deliverables
    - What's the MVP? (this is supposed to be a prototype)
- project plan

# To-do

- [x]  List research topics
- [x]  List research resources
- [x]  Scope the research
