### ISSUE TITLE
Wake Word project prototype deliverables

### ISSUE THREAD

**Issue by secretsauceai** [secretsauceai/secret_sauce_ai#15]
# Description

Complete the prototype deliverables:

- Wake Word Collector (recorder) script
- Wake Word Data Prep script
- Precise TF2 (binaries?) runner only and conversion of compressed models
- Documentation

# To-do

## Scripts

- [x]  Wake Word Collector script
- [x]  Wake Word Collector revised project overview
- [x]  Wake Word Collector revise readme
- [x]  Wake Word Data Prep script (MVP)
    - [x]  Split of 50/50 directories (see this [issue](https://github.com/AmateurAcademic/wakeword-data-prep/issues/8) and this [one](https://github.com/AmateurAcademic/wakeword-data-prep/issues/7))
    - [x]  Gaussian noise ([issue](https://github.com/AmateurAcademic/wakeword-data-prep/issues/5))
    - [x]  Background noise mixing (uses method in Precise, exclude the Gaussian directories of course!)
    - [x]  Revise readme
- [x] Training protocol  (step-by-step training guide, perhaps automate all of it?)
- [x]  Wake Word Data Prep script (release)
    - [x]  Include precise methods listen or iterative training?
    - [x]  clean script
    - [x]  Wake Word Data Prep revised documentation
    - [x]  Wake word CLI

## ML

Each step usually consists of training several (at least 5) models (using the same and other collected data to remove bias) and evaluating their results to ensure that the models aren't randomly performing well. 

- [x]  Models (first tf1.13, then tflite) must pass minimum quality control: 5 wake up in a row, 2h random input (ie 1h TV and 1h conversation) without false wake up
    - [x]  tf 1.13
- [x]  Models must pass production quality control: 1 week: wake up every time, ~2-3 false wake ups (future goal: 1 false wake up per week!)
    - [x]  tf1.13
        - sensitivity is too high, requires parameter tweaking, but once tweaked it passes all quality controls
- [x]  Further utterance based not-wake 'incremental' (ie common voice) training
    - current amount of common voice: ~30k, increase to ~40k
    - [x]  perform analysis for unbalanced classes, size as needed (maximize the number of not-wake samples without breaking the model's class balance)

## Precise tflite
- [x]  Make branch for just the runner (engine) of Precise TF2
- [x]  Create slimmed down tflite binaries(?) of runner branch

**Comment by secretsauceai** [comment]
I've had a bit of a blocker on these deliverables, specifically for ensuring production models for each run of the scripts. This becomes even more of an issue when converting to tflite. 

# Blocker
Models can often be (unpredictable!) produced that lack features required. The models only lock onto specific features instead of the collection of features. This results in the model's sensitivity being too high or too low (which is actually a symptom of a deeper problem).

## Description
The wake word deliverables need to be seen as a data pipeline:
* efficient, sparse data collection
* generation and splitting of the collected data optimally
* training the model to completion resulting in a production wake word model

A tweak to data collection means the whole process needs to be slightly changed (and therefore also the scripts I write all need to be amended throughout the whole pipeline). 

The data collection must collect the important use cases that a model would need to learn from. Normally, when you have thousands or even millions of samples, you can rely on the model to 'figure out' those features by itself. However when you are dealing in sparse data, you don't have this luxury. You need to perform old school feature engineering in your data set. 

With that in mind, the blocker I face is forcing the model being trained not to be 'too lazy' and focus on a couple of features instead of a whole sequence of them (this is a time series after all, and a GRU is an RNN) every time.

## Possible solution
To mitigate this, I have tried many approaches. My current hypothesis to eliminate these 'partial feature matches', is to chop up a random sampling of 'wake-word' category audio files into tiny bits (I had to figure out how tiny, that took a while), and feed those into the 'not-wake-word' category. 

Those chopped files will also be Gaussed and mixed with background noise later on, increasing the number of samples. 

I have already written a small script and tested the results. 

## Next step
Whenever I have time again, I will run this new data set a few times and check the results in my production environment. This solution might also allow 2 less recording sessions in the wake-word-recorder-py (paragraph and syllables).

**Comment by secretsauceai** [comment]
One of these tasks needs to be reviewed, [this repo](https://github.com/OpenVoiceOS/precise_lite_runner), might be a good solution to a slimmed down runner. It also uses tflit over tf2 for tflite. It needs to be tested, but this is amazing @JarbasAI good work!

**Comment by secretsauceai** [comment]
tflite models will be moved to phase 2 scope
